// <autogenerated>
//   This file was generated by T4 code generator IServiceTemplate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;
using ZSZ.Model.Models.Custom;
using ZSZ.Model.Models;
using ZSZ.Model.Models.DTO;


namespace ZSZ.IService
{
    public interface ISysMenusService : IBaseService<T_SysMenus>
    {
        /// <summary>
        /// 根据用户ID获取菜单
        /// </summary>
        /// <param name="userId"></param>
        /// <returns>List(SysMenu)</returns>
        MsgResult GetSysMenusByUserId(int userId);

        /// <summary>
        /// 获取所有的菜单树节点
        /// </summary>
        /// <returns></returns>
        MsgResult GetZtreeNodeByUserId();

        /// <summary>
        /// 获取点击菜单节点详情数据
        /// </summary>
        /// <returns></returns>
        MsgResult GetZtreeNodeDetailById(int id);

        /// <summary>
        /// 菜单名或者地址是否重复
        /// </summary>
        /// <param name="menuName"></param>
        /// <param name="url"></param>
        /// <returns></returns>
        MsgResult IsRepeatedMenuNameOrUrl(string menuName, string url);

        /// <summary>
        /// 是否缺乏必须的添加信息
        /// </summary>
        /// <param name="menu"></param>
        /// <returns></returns>
        MsgResult IsLackRuquiredMenuInfo(SysMenu menu);


    }
}
