// <autogenerated>
//   This file was generated by T4 code generator IServiceTemplate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;
using ZSZ.Model.Models.Custom;
using ZSZ.Model.Models;


namespace ZSZ.IService
{
    public interface ISysRolesService : IBaseService<T_SysRoles>
    {
       
    }
}
