// <autogenerated>
//   This file was generated by T4 code generator IServiceTemplate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;
using ZSZ.Model.Models.Custom;
using ZSZ.Model.Models;


namespace ZSZ.IService
{
    public interface ISysMenusService : IBaseService<T_SysMenus>
    {
        /// <summary>
        /// 根据用户ID获取菜单
        /// </summary>
        /// <param name="userId"></param>
        /// <returns>List(SysMenu)</returns>
        MsgResult GetSysMenusByUserId(int userId);

        /// <summary>
        /// 获取所有的菜单树节点
        /// </summary>
        /// <returns></returns>
        MsgResult GetZtreeNodeByUserId();
    }
}
