// <autogenerated>
//   This file was generated by T4 code generator IDalTemplate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using ZSZ.IDAL;
using ZSZ.Model.Models;

namespace ZSZ.IDAL
{
    public interface ISysRolesDal: IBaseDal<T_SysRoles>
    {
       
    }
}
