// <autogenerated>
//   This file was generated by T4 code generator IDalTemplate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System.Collections.Generic;
using ZSZ.IDAL;
using ZSZ.Model.Models;

namespace ZSZ.IDAL
{
    public interface ISysOperationsDal: IBaseDal<T_SysOperations>
    {
        /// <summary>
        /// 通过角色ID获取角色所有的操作
        /// </summary>
        /// <param name="roleId">角色Id</param>
        /// <returns></returns>
        List<T_SysOperations> GetSysOperationListByRoleId(int roleId);
    }
}
