// <autogenerated>
//   This file was generated by T4 code generator IDalTemplate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System.Collections.Generic;
using ZSZ.IDAL;
using ZSZ.Model.Models;

namespace ZSZ.IDAL
{
    public interface ISysMenusDal: IBaseDal<T_SysMenus>
    {
        /// <summary>
        /// 根据用户ID获取菜单
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        List<T_SysMenus> GetSysMenusByUserId(int userId);

      
    }
}
