// <autogenerated>
//   This file was generated by T4 code generator DalTemplate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using ZSZ.IDAL;
using ZSZ.Model.Models;
using ZSZ.DAL;

namespace ZSZ.IDAL
{
    public class MenuPermissionsDal : BaseDal<T_MenuPermissions> , IMenuPermissionsDal
    {
       
    }
}
