// <autogenerated>
//   This file was generated by T4 code generator ServiceTemplate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using ZSZ.Common;
using ZSZ.IDAL;
using ZSZ.IService;
using ZSZ.Model.Models;


namespace ZSZ.Service
{
    public class SysMenusService : BaseService<T_SysMenus> , ISysMenusService
    {
       
    }
}
