// <autogenerated>
//   This file was generated by T4 code generator ServiceTemplate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using log4net;
using Newtonsoft.Json;
using ZSZ.Common;
using ZSZ.IDAL;
using ZSZ.IService;
using ZSZ.Model.Models;
using ZSZ.Model.Models.Custom;
using ZSZ.Model.Models.Custom.ztree;
using ZSZ.Model.Models.DTO;

namespace ZSZ.Service
{
    public class SysMenusService : BaseService<T_SysMenus>, ISysMenusService
    {
        //public ILog Logger { get; set; }
        public ISysMenusDal SysMenusDal { get; set; }


        /// <summary>
        /// 获取用户的菜单
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        public MsgResult GetSysMenusByUserId(int userId)
        {
            MsgResult result = new MsgResult();
            try
            {
                List<T_SysMenus> list = SysMenusDal.GetSysMenusByUserId(userId);
                if (list.Count <= 0)
                {
                    result.IsSuccess = false;
                    result.Message = "当前用户未分配菜单";
                }
                else
                {
                    List<SysMenu> menuList = list.Select(x => Mapper.Map<SysMenu>(x)).ToList();
                    result.IsSuccess = true;
                    result.Data = JsonConvert.SerializeObject(menuList);
                }
            }
            catch (Exception ex)
            {
                result.IsSuccess = false;
                result.Message = ex.Message;
                //Logger.Error(ex.Message);
            }

            return result;
        }

        /// <summary>
        /// 获取所有的菜单树节点
        /// </summary>
        /// <returns></returns>
        public MsgResult GetZtreeNodeByUserId()
        {
            MsgResult result = new MsgResult();
            try
            {
                List<ZtreeNode> nodeList = new List<ZtreeNode>();
                List<T_SysMenus> sysMenus = SysMenusDal.GetModel(x => x.Id >= 0).ToList();
                for (int i = 0; i < sysMenus.Count; i++)
                {
                    ZtreeNode node = new ZtreeNode();
                    node.Id = sysMenus[i].Id;
                    node.Name = sysMenus[i].MenuName;
                    node.Pid = sysMenus[i].ParentId;
                    nodeList.Add(node);
                }
                result.IsSuccess = true;
                result.Data = JsonConvert.SerializeObject(nodeList);
            }
            catch (Exception ex)
            {
                result.IsSuccess = false;
                result.Message = ex.Message;
            }
            return result;
        }
    }
}
